export const ERROR_STATUS = {
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
  SERVER_CONFLICT: 409,
  TOO_MANY_REQUEST: 429,
  SERVER_UNAVAILABLE: 503,
};

export const ERROR_CODE = {
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  SERVER_ERROR: 'SERVER_ERROR',
  SERVER_CONFLICT: 'SERVER_CONFLICT',
  TOO_MANY_REQUEST: 'TOO_MANY_REQUEST',
  SERVER_UNAVAILABLE: 'SERVER_UNAVAILABLE',
};

export const SUCCESS_STATUS = 200;
